### PR TITLE
Integrate suggestions according to #45

### PR DESCRIPTION
**Pull request by LienReyserhove**
I integrated the suggestions as specified in #45. 

For each species found **in only one region**, both `establishmentMeans`, `eventDate` and `occurrenceStatus` was provided.
When a species was found in more than one region, only `occurrenceStatus `was provided for each region, and `establishmentMeans`, `eventDate` and `occurrenceStatus` were given for Belgium.

I generated 4 new columns: `Flanders`, `Brussels`,`Wallonia` and `Belgium`. 
The content of these columns refers to the specific occurrence of a species on a regional or national level: `S` if present in a single region or in Belgium, `?` if presence uncertain, `NA` if absent and `M` if present in multiple regions.

The rationele behind my approach is to attribute an **`"S"`** as presence status when this particular species is present **in one region only** (see table below). This special presence status is than used further in the mapping, more specifically to attribute values for `eventDate` and `establishmentMeans``(i.e. case_when (Flanders == "S" ~ Date, Flanders != "S" ~"")`

This should look like this:

|raw_presence_fl |raw_presence_br |raw_presence_wa |Flanders |Brussels |Wallonia |Belgium |
|:---------------|:---------------|:---------------|:--------|:--------|:--------|:-------|
|X               |NA              |NA              |S        |NA       |NA       |S       |
|NA              |X               |NA              |NA       |S        |NA       |S       |
|NA              |NA              |X               |NA       |NA       |S        |S       |
|X               |X               |NA              |M        |M        |NA       |S       |
|X               |NA              |X               |M        |NA       |M        |S       |
|NA              |X               |X               |NA       |M        |M        |S       |
|NA              |NA              |NA              |NA       |NA       |NA       |NA      |
|X               |?               |NA              |S        |?        |NA       |S       |
|X               |NA              |?               |S        |NA       |?        |S       |
|X               |X               |?               |M        |M        |?        |S       |

### CODE REVIEW

**Comment by peterdesmet** [comment]
* Looks good!
* Can you update your comment and provide a table with the 8 use cases? + some `?` examples. And even better: add it to Rmd file.
* `?`+ `?` + `X` => single region

**Comment by peterdesmet** [comment]
Would use the following intermediate statuses for all regions (including Belgium):

* `S`: single region
* `M`: multiple regions (was `X`)
* `?`: presence uncertain
* `(empty)`: absent

Only records with `S` get the full information (including dates, pathway), rest gets `occurrenceStatus`, `absent` is not added (pending answer on https://github.com/trias-project/alien-plants-belgium/issues/45#issuecomment-351099040)

**Comment by LienReyserhove** [comment]
Thanks for the review, I integrated this in the new script, see my [earlier comment](https://github.com/trias-project/alien-plants-belgium/pull/47#issue-281103531).

**Comment by qgroom** [comment]
Hi Lien,
I'm afraid I am rather lost as it is not easy to follow on GitHub updates.
However, perhaps you could present you solution at next week's meeting.
Quentin

**Comment by LienReyserhove** [comment]
I'm happy to explain explain this next week!

**Pull request merged**
