### PR TITLE
Standardize pathway

### PR DESCRIPTION
**Pull request by LienReyserhove**
I integrated the temporary vocabulary as suggested for TrIAS (see [this link](https://github.com/trias-project/vocab/blob/master/vocabulary/pathway/pathway.tsv)) for the pathway description. Similar as for the [alien macroinverterates checklist](https://github.com/trias-project/alien-macroinvertebrates), I added the reference to the [CBD standard](https://www.cbd.int/doc/meetings/sbstta/sbstta-18/official/sbstta-18-09-add1-en.pdf), which is the source of our suggested vocabulary.

@peterdesmet: By accident, I pushed the changes in taxon.csv, which removes the UTF-8 encoding from `scientificName`. Integration of the suggestions in #41 did not work, so, could you please rerun the code?

### CODE REVIEW

**Comment by peterdesmet** [comment]
Nice! Maybe one suggestion: I would use simple values in the recoding, add a step with `paste("cbd_2014_pathway", value, sep = ":")` for **non blank values** and then show the preview.

**Comment by peterdesmet** [comment]
I'll rerun when you let me know.

**Comment by LienReyserhove** [comment]
@peterdesmet I integrated the requested changes. Could you rerun the code to generate the correct encoding?

**Comment by peterdesmet** [comment]
Done. Green button is waiting for you.

**Pull request merged**
